### ISSUE TITLE
The Logger.py is not working 

### ISSUE THREAD

**Issue by WalnutLamb14243** [MCServerScout/Discord-Bot#75]
Logger not callable
![image](https://github.com/MCServerScout/Discord-Bot/assets/148599832/5eef13ec-2505-434a-b902-10eefd37373f)

**Comment by Pilot1782** [comment]
Can you provide a directory tree, and try and follow the setup guide [here](https://github.com/MCServerScout/Discord-Bot/wiki/Setup).

**Comment by WalnutLamb14243** [comment]
sure

**Comment by WalnutLamb14243** [comment]
lemme try to follow setup guide

**Comment by WalnutLamb14243** [comment]
also how tf u run the bot

**Comment by WalnutLamb14243** [comment]
![image](https://github.com/MCServerScout/Discord-Bot/assets/148599832/4e1eab69-2251-4bb5-99c8-4dc0568d1654)
 i Tried follow the setup but it just gimme that mess
here the text if u want C:\Users\Temp\Downloads\Discord-Bot-master\Discord-Bot-master>python3 botHandler.pyw

----------
Updating files
Traceback (most recent call last):
  File "C:\Users\Temp\Downloads\Discord-Bot-master\Discord-Bot-master\botHandler.pyw", line 188, in <module>
    main()
  File "C:\Users\Temp\Downloads\Discord-Bot-master\Discord-Bot-master\botHandler.pyw", line 162, in main
    download_zip()
  File "C:\Users\Temp\Downloads\Discord-Bot-master\Discord-Bot-master\botHandler.pyw", line 84, in download_zip
    subprocess.call(["mkdir", git_dir])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\Temp\Downloads\Discord-Bot-master\Discord-Bot-master>python3 botHandler.py

**Comment by WalnutLamb14243** [comment]
do i need to do sentry uri or anything

**Comment by Pilot1782** [comment]
Can you open the directory and run `tree` and the handler assumes a Linux os, you can use wsl or a vm.

**Comment by Pilot1782** [comment]
Changed the setup guide which can now be found [here](https://github.com/MCServerScout/Discord-Bot/blob/dev-builds/docs/EU_Docs/setup.md), try that and let me know how it goes.
